
<!-- Generated by ai2html v0.121.0 - 2024-04-23 11:43 -->
<!-- ai file: rafah-zoom.ai -->
<style media="screen,print">
	.g-rafah-zoom-box {
		container-type: inline-size;
	}
	.g-rafah-zoom-box, .g-artboard {
		margin:0 auto;
	}
	p {
		margin:0;
	}
	.g-aiAbs {
		position:absolute;
	}
	.g-aiImg {
		position:absolute;
		top:0;
		display:block;
		width:100% !important;
	}
	.g-aiSymbol {
		position: absolute;
		box-sizing: border-box;
	}
	.g-aiPointText p { white-space: nowrap; }
	.g-artboard {
		display: none;
	}
	.visible {
		display: block;
	}
	.g-rafah-zoom-desktop {
		position:relative;
		overflow:hidden;
	}
	.g-rafah-zoom-desktop p {
		font-family:nyt-franklin,arial,helvetica,sans-serif;
		font-weight:normal;
		line-height:17px;
		height:auto;
		opacity:1;
		letter-spacing:0em;
		font-size:15px;
		text-align:left;
		color:rgb(255,255,255);
		top:1.2px;
		position:static;
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
	}
	.g-rafah-zoom-desktop .g-pstyle0 {
		font-weight:500;
		height:17px;
		position:relative;
	}
	.g-rafah-zoom-desktop .g-pstyle1 {
		font-weight:500;
		height:17px;
		font-size:24px;
		color:rgb(252,0,0);
		top:1.9px;
		position:relative;
	}
	.g-rafah-zoom-desktop .g-pstyle2 {
		font-weight:500;
		height:17px;
		letter-spacing:0.025em;
		position:relative;
	}
	.g-rafah-zoom-desktop .g-pstyle3 {
		font-weight:500;
		line-height:30px;
		height:30px;
		opacity:0.5;
		letter-spacing:0.025em;
		font-size:25px;
		top:2px;
		position:relative;
	}
	.g-rafah-zoom-desktop .g-pstyle4 {
		font-weight:700;
		height:17px;
		color:rgb(234,126,52);
		position:relative;
	}
	.g-rafah-zoom-desktop .g-pstyle5 {
		font-weight:500;
		height:17px;
		text-align:right;
		position:relative;
	}
	.g-rafah-zoom-desktop .g-cstyle0 {
		font-size:24px;
	}
	.g-rafah-zoom-desktop .g-cstyle1 {
		font-size:24px;
		color:rgb(252,0,0);
	}
	@container (min-width: 600px) and (max-width: 99999999px) {
		.g-rafah-zoom-desktop {
			display: block;
		}
	}
	.g-rafah-zoom-Artboard_2 {
		position:relative;
		overflow:hidden;
	}
	.g-rafah-zoom-Artboard_2 p {
		font-family:nyt-franklin,arial,helvetica,sans-serif;
		font-weight:normal;
		line-height:14px;
		height:auto;
		opacity:1;
		letter-spacing:0.025em;
		font-size:13px;
		text-align:left;
		color:rgb(255,255,255);
		top:1px;
		position:static;
		text-transform:none;
		padding-bottom:0;
		padding-top:0;
		mix-blend-mode:normal;
		font-style:normal;
	}
	.g-rafah-zoom-Artboard_2 .g-pstyle0 {
		font-weight:500;
		line-height:17px;
		height:17px;
		letter-spacing:0em;
		position:relative;
	}
	.g-rafah-zoom-Artboard_2 .g-pstyle1 {
		font-weight:500;
		height:14px;
		position:relative;
	}
	.g-rafah-zoom-Artboard_2 .g-pstyle2 {
		font-weight:500;
		line-height:18px;
		height:18px;
		opacity:0.5;
		font-size:15px;
		top:1.2px;
		position:relative;
	}
	.g-rafah-zoom-Artboard_2 .g-pstyle3 {
		font-weight:700;
		height:14px;
		color:rgb(234,126,52);
		position:relative;
	}
	.g-rafah-zoom-Artboard_2 .g-pstyle4 {
		font-weight:500;
		height:14px;
		text-align:right;
		position:relative;
	}
	@container (min-width: 0px) and (max-width: 599px) {
		.g-rafah-zoom-Artboard_2 {
			display: block;
		}
	}

	/* Custom CSS */
	.g-text-shadow-dark {
    text-shadow: 0px 0px 2px rgba(0,0,0,.5), 0px 0px 2px rgba(0,0,0,.5), 0px 0px 2px rgba(0,0,0,.5), 0px 0px 1px rgba(0,0,0,.5);
    -webkit-font-smoothing: antialiased;
}

</style>

<div class="g-rafah-zoom-box ai2html ai2html-responsive" bind:clientWidth>

	<!-- Artboard: rafah-zoom-desktop -->
	<div class="g-rafah-zoom-desktop g-artboard" style="min-width: 600px;" data-aspect-ratio="1.368" data-min-width="600" class:visible={600 <= clientWidth && clientWidth <= Infinity}>
<div style="padding: 0 0 73.1051% 0;"></div>
		<img id="g-rafah-zoom-desktop-img" class="g-rafah-zoom-desktop-img g-aiImg" alt="" loading="lazy" src="_assets/rafah-zoom-desktop.jpg"/>
		<div id="g-ai0-1" class="g-text-shadow-dark g-aiAbs g-aiPointText" style="top:7.4118%;margin-top:-30.5px;left:0.7277%;width:151px;">
			<p class="g-pstyle0">1,000 <span class="g-cstyle0">fe</span><span class="g-cstyle1">et</span></p>
			<p class="g-pstyle1">is a long way</p>
			<p class="g-pstyle1">to go</p>
		</div>
		<div id="g-ai0-2" class="g-text-shadow-dark g-aiAbs g-aiPointText" style="top:13.881%;margin-top:-25.8px;left:67.7822%;width:69px;">
			<p class="g-pstyle0">Crowds</p>
			<p class="g-pstyle0">waiting</p>
			<p class="g-pstyle0">at gate</p>
		</div>
		<div id="g-ai0-3" class="g-text-shadow-dark g-aiAbs g-aiPointText" style="top:19.5901%;margin-top:-8.8px;left:43.739%;width:80px;">
			<p class="g-pstyle2">Blasts tk</p>
		</div>
		<div id="g-ai0-4" class="g-text-shadow-dark g-aiAbs g-aiPointText" style="top:28.6321%;margin-top:-15.4px;left:8.0742%;width:125px;">
			<p class="g-pstyle3">{country}</p>
		</div>
		<div id="g-ai0-5" class="g-text-shadow-dark g-aiAbs g-aiPointText" style="top:28.6321%;margin-top:-15.4px;left:81.4549%;width:83px;">
			<p class="g-pstyle3">GAZA</p>
		</div>
		<div id="g-ai0-6" class="g-text-shadow-dark g-aiAbs g-aiPointText" style="top:48.7064%;margin-top:-17.3px;left:46.5702%;width:66px;">
			<p class="g-pstyle0">Strike</p>
			<p class="g-pstyle0">craters</p>
		</div>
		<div id="g-ai0-7" class="g-text-shadow-dark g-aiAbs g-aiPointText" style="top:51.4467%;margin-top:-17.3px;left:49.1826%;width:121px;">
			<p class="g-pstyle0">Craters from</p>
			<p class="g-pstyle0">previous strikes</p>
		</div>
		<div id="g-ai0-8" class="g-text-shadow-dark g-aiAbs g-aiPointText" style="top:54.4069%;margin-top:-17.2px;left:29.6463%;width:78px;">
			<p class="g-pstyle4">Rafah</p>
			<p class="g-pstyle4">crossing</p>
		</div>
		<div id="g-ai0-9" class="g-text-shadow-dark g-aiAbs g-aiPointText" style="top:68.2315%;margin-top:-8.8px;right:79.2035%;width:52px;">
			<p class="g-pstyle5">Gate</p>
		</div>
		<div id="g-ai0-10" class="g-text-shadow-dark g-aiAbs g-aiPointText" style="top:77.5944%;margin-top:-8.8px;left:54.3525%;width:135px;">
			<p class="g-pstyle0">Additional fencing</p>
		</div>
		<div id="g-ai0-11" class="g-text-shadow-dark g-aiAbs g-aiPointText" style="top:91.9811%;margin-top:-25.8px;left:13.3431%;width:131px;">
			<p class="g-pstyle0">Humanitarian aid</p>
			<p class="g-pstyle0">trucks waiting</p>
			<p class="g-pstyle0">along road</p>
		</div>
	</div>

	<!-- Artboard: rafah-zoom-Artboard_2 -->
	<div class="g-rafah-zoom-Artboard_2 g-artboard" style="max-width: 599px;max-height: 550px" data-aspect-ratio="1.089" data-min-width="0" data-max-width="599" class:visible={0 <= clientWidth && clientWidth <= 599}>
<div style="padding: 0 0 91.7942% 0;"></div>
		<img id="g-rafah-zoom-Artboard_2-img" class="g-rafah-zoom-Artboard_2-img g-aiImg" alt="" loading="lazy" src="_assets/rafah-zoom-Artboard_2.jpg"/>
		<div id="g-ai1-1" class="g-text-shadow-dark g-aiAbs g-aiPointText" style="top:5.8349%;margin-top:-8.7px;left:1.3609%;width:80px;">
			<p class="g-pstyle0">1,000 feet</p>
		</div>
		<div id="g-ai1-2" class="g-text-shadow-dark g-aiAbs g-aiPointText" style="top:14.9131%;margin-top:-21.2px;left:77.6683%;width:65px;">
			<p class="g-pstyle1">Crowds</p>
			<p class="g-pstyle1">waiting</p>
			<p class="g-pstyle1">at gate</p>
		</div>
		<div id="g-ai1-3" class="g-text-shadow-dark g-aiAbs g-aiPointText" style="top:31.2345%;margin-top:-9.3px;left:4.4643%;width:84px;">
			<p class="g-pstyle2">{country}</p>
		</div>
		<div id="g-ai1-4" class="g-text-shadow-dark g-aiAbs g-aiPointText" style="top:31.2345%;margin-top:-9.3px;left:84.4763%;width:59px;">
			<p class="g-pstyle2">GAZA</p>
		</div>
		<div id="g-ai1-5" class="g-text-shadow-dark g-aiAbs g-aiPointText" style="top:47.8914%;margin-top:-14.2px;left:51.9993%;width:63px;">
			<p class="g-pstyle1">Strike</p>
			<p class="g-pstyle1">craters</p>
		</div>
		<div id="g-ai1-6" class="g-text-shadow-dark g-aiAbs g-aiPointText" style="top:55.6608%;margin-top:-14.2px;left:27.9496%;width:73px;">
			<p class="g-pstyle3">Rafah</p>
			<p class="g-pstyle3">crossing</p>
		</div>
		<div id="g-ai1-7" class="g-Layer_1 g-aiAbs g-aiPointText" style="top:67.1596%;margin-top:-7.2px;right:80.2585%;width:49px;">
			<p class="g-pstyle4">Gate</p>
		</div>
		<div id="g-ai1-8" class="g-text-shadow-dark g-aiAbs g-aiPointText" style="top:72.3473%;margin-top:-14.2px;left:59.1129%;width:141px;">
			<p class="g-pstyle1">Additional fencing</p>
			<p class="g-pstyle1">apparent on satellite</p>
		</div>
		<div id="g-ai1-9" class="g-text-shadow-dark g-aiAbs g-aiPointText" style="top:90.5037%;margin-top:-21.2px;left:11.6178%;width:122px;">
			<p class="g-pstyle1">Humanitarian aid</p>
			<p class="g-pstyle1">trucks waiting</p>
			<p class="g-pstyle1">along road</p>
		</div>
	</div>

</div>


<script>
  import { onMount } from "svelte";
let clientWidth = -1; 
export let country = "";
  onMount(() => {
  });

</script>
<!-- End ai2html - 2024-04-23 11:43 -->
